JOBS = [
    # Bangalore — React
    {"title": "Senior React Developer", "company": "Flipkart", "location": "Bangalore",
     "skills": "React, TypeScript, Redux, Webpack", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 1800000, "salary_max": 2500000,
     "description": "Build high-scale e-commerce UIs. Own frontend architecture for catalog pages.",
     "posted_at": "2026-04-01", "is_open": 1},
    {"title": "React Lead Engineer", "company": "Swiggy", "location": "Bangalore",
     "skills": "React, Node.js, GraphQL, Docker", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2200000, "salary_max": 3000000,
     "description": "Lead a team of 5 engineers building the consumer ordering platform.",
     "posted_at": "2026-04-05", "is_open": 1},
    {"title": "React Developer", "company": "Meesho", "location": "Bangalore",
     "skills": "React, JavaScript, CSS, REST APIs", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1200000, "salary_max": 1800000,
     "description": "Develop responsive seller dashboard components for the Meesho platform.",
     "posted_at": "2026-03-28", "is_open": 1},
    {"title": "Junior React Developer", "company": "Urban Company", "location": "Bangalore",
     "skills": "React, JavaScript, HTML, CSS", "job_type": "full-time",
     "experience_level": "junior", "salary_min": 600000, "salary_max": 900000,
     "description": "Build and maintain customer-facing features under senior guidance.",
     "posted_at": "2026-04-10", "is_open": 1},
    {"title": "Frontend Engineer (React)", "company": "Zepto", "location": "Bangalore",
     "skills": "React, Next.js, Tailwind CSS, TypeScript", "job_type": "remote",
     "experience_level": "mid", "salary_min": 1500000, "salary_max": 2200000,
     "description": "Build the consumer-facing quick commerce app with a focus on performance.",
     "posted_at": "2026-04-08", "is_open": 1},
    # Bangalore — Python / Data
    {"title": "Senior Python Engineer", "company": "Razorpay", "location": "Bangalore",
     "skills": "Python, FastAPI, PostgreSQL, Kafka", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2000000, "salary_max": 2800000,
     "description": "Design payment processing microservices handling millions of transactions daily.",
     "posted_at": "2026-04-02", "is_open": 1},
    {"title": "Data Scientist", "company": "PhonePe", "location": "Bangalore",
     "skills": "Python, scikit-learn, SQL, Spark", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1600000, "salary_max": 2200000,
     "description": "Build ML models for fraud detection and credit risk assessment.",
     "posted_at": "2026-03-25", "is_open": 1},
    {"title": "Junior Data Scientist", "company": "Byju's", "location": "Bangalore",
     "skills": "Python, pandas, NumPy, machine learning", "job_type": "full-time",
     "experience_level": "junior", "salary_min": 700000, "salary_max": 1100000,
     "description": "Analyse student learning patterns and build recommendation models.",
     "posted_at": "2026-04-12", "is_open": 1},
    {"title": "ML Engineer", "company": "CRED", "location": "Bangalore",
     "skills": "Python, TensorFlow, Docker, Kubernetes", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2500000, "salary_max": 3500000,
     "description": "Build and deploy real-time ML inference pipelines for credit scoring.",
     "posted_at": "2026-04-06", "is_open": 1},
    # Bangalore — DevOps / Java
    {"title": "DevOps Engineer", "company": "Ola", "location": "Bangalore",
     "skills": "AWS, Kubernetes, Terraform, Jenkins", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1400000, "salary_max": 2000000,
     "description": "Manage cloud infrastructure for ride-hailing services at scale.",
     "posted_at": "2026-04-03", "is_open": 1},
    {"title": "Senior DevOps Engineer", "company": "Flipkart", "location": "Bangalore",
     "skills": "AWS, Docker, Kubernetes, Python, CI/CD", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2200000, "salary_max": 3000000,
     "description": "Own infrastructure reliability for Flipkart's compute platform.",
     "posted_at": "2026-03-20", "is_open": 1},
    {"title": "Java Backend Developer", "company": "Infosys", "location": "Bangalore",
     "skills": "Java, Spring Boot, Hibernate, MySQL", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1000000, "salary_max": 1600000,
     "description": "Develop enterprise microservices for banking clients.",
     "posted_at": "2026-04-07", "is_open": 1},
    # Chennai — various
    {"title": "Senior React Developer", "company": "Zoho", "location": "Chennai",
     "skills": "React, JavaScript, Redux, REST APIs", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 1600000, "salary_max": 2200000,
     "description": "Build next-gen SaaS product UIs for Zoho's CRM suite.",
     "posted_at": "2026-04-04", "is_open": 1},
    {"title": "Python Developer", "company": "Freshworks", "location": "Chennai",
     "skills": "Python, Django, PostgreSQL, Redis", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1200000, "salary_max": 1800000,
     "description": "Build backend APIs for Freshdesk's helpdesk ticketing platform.",
     "posted_at": "2026-04-01", "is_open": 1},
    {"title": "QA Engineer", "company": "Zoho", "location": "Chennai",
     "skills": "Selenium, Python, TestNG, JIRA", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 800000, "salary_max": 1200000,
     "description": "Design and execute automated test suites for Zoho Books.",
     "posted_at": "2026-03-30", "is_open": 1},
    {"title": "Junior Java Developer", "company": "TCS", "location": "Chennai",
     "skills": "Java, Spring, MySQL, REST", "job_type": "full-time",
     "experience_level": "junior", "salary_min": 500000, "salary_max": 800000,
     "description": "Develop and maintain backend services for banking projects.",
     "posted_at": "2026-04-11", "is_open": 1},
    {"title": "DevOps Engineer", "company": "Freshworks", "location": "Chennai",
     "skills": "AWS, Docker, Ansible, Linux", "job_type": "remote",
     "experience_level": "mid", "salary_min": 1300000, "salary_max": 1900000,
     "description": "Automate deployments and maintain cloud infrastructure for SaaS products.",
     "posted_at": "2026-04-09", "is_open": 1},
    {"title": "Android Developer", "company": "Zoho", "location": "Chennai",
     "skills": "Android, Kotlin, Jetpack Compose, REST APIs", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1100000, "salary_max": 1700000,
     "description": "Build native Android apps for Zoho's mobile product suite.",
     "posted_at": "2026-04-02", "is_open": 1},
    # Mumbai — various
    {"title": "Senior Python Developer", "company": "Paytm", "location": "Mumbai",
     "skills": "Python, Django, Celery, Redis, PostgreSQL", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 1900000, "salary_max": 2600000,
     "description": "Build scalable payment and wallet backend services.",
     "posted_at": "2026-04-03", "is_open": 1},
    {"title": "React Developer", "company": "Paytm", "location": "Mumbai",
     "skills": "React, JavaScript, TypeScript, REST APIs", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1300000, "salary_max": 1900000,
     "description": "Develop checkout and payment flows for Paytm's web platform.",
     "posted_at": "2026-04-06", "is_open": 1},
    {"title": "Data Scientist (Senior)", "company": "Reliance Jio", "location": "Mumbai",
     "skills": "Python, PySpark, ML, SQL, Hadoop", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2200000, "salary_max": 3000000,
     "description": "Build data pipelines and recommendation models for Jio's media platform.",
     "posted_at": "2026-03-27", "is_open": 1},
    {"title": "iOS Developer", "company": "Dream11", "location": "Mumbai",
     "skills": "Swift, iOS, UIKit, REST APIs, Xcode", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1400000, "salary_max": 2100000,
     "description": "Build and optimise the Dream11 iOS app for fantasy sports.",
     "posted_at": "2026-04-10", "is_open": 1},
    {"title": "Product Manager", "company": "Nykaa", "location": "Mumbai",
     "skills": "Product Management, Agile, SQL, Analytics", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2500000, "salary_max": 3500000,
     "description": "Own the checkout and payments product for Nykaa's e-commerce platform.",
     "posted_at": "2026-04-01", "is_open": 1},
    {"title": "Node.js Developer", "company": "BookMyShow", "location": "Mumbai",
     "skills": "Node.js, Express, MongoDB, Redis", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1200000, "salary_max": 1800000,
     "description": "Build ticket booking APIs that handle peak concert-day traffic.",
     "posted_at": "2026-04-08", "is_open": 1},
    {"title": "Junior QA Engineer", "company": "Nykaa", "location": "Mumbai",
     "skills": "Selenium, Java, TestNG, Git", "job_type": "full-time",
     "experience_level": "junior", "salary_min": 500000, "salary_max": 800000,
     "description": "Write and run automated regression tests for the Nykaa shopping app.",
     "posted_at": "2026-04-13", "is_open": 1},
    # Hyderabad — various
    {"title": "Senior Java Developer", "company": "Microsoft IDC", "location": "Hyderabad",
     "skills": "Java, Spring Boot, Azure, Microservices", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2500000, "salary_max": 3500000,
     "description": "Build cloud-native services for Microsoft Azure's identity platform.",
     "posted_at": "2026-04-05", "is_open": 1},
    {"title": "Python Engineer", "company": "Amazon", "location": "Hyderabad",
     "skills": "Python, AWS Lambda, DynamoDB, CDK", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1800000, "salary_max": 2500000,
     "description": "Build serverless data processing pipelines for Amazon's logistics platform.",
     "posted_at": "2026-04-02", "is_open": 1},
    {"title": "DevOps / SRE", "company": "Google", "location": "Hyderabad",
     "skills": "Kubernetes, GCP, Python, Prometheus, Go", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 3000000, "salary_max": 4500000,
     "description": "Ensure reliability of Google's search infrastructure serving Indian users.",
     "posted_at": "2026-03-31", "is_open": 1},
    {"title": "React Developer (Contract)", "company": "Wipro", "location": "Hyderabad",
     "skills": "React, JavaScript, CSS, JIRA", "job_type": "contract",
     "experience_level": "mid", "salary_min": 1000000, "salary_max": 1400000,
     "description": "6-month contract to build UI components for a banking client portal.",
     "posted_at": "2026-04-07", "is_open": 1},
    {"title": "Data Engineer", "company": "Deloitte", "location": "Hyderabad",
     "skills": "Python, Spark, Airflow, AWS, SQL", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1400000, "salary_max": 2000000,
     "description": "Build and maintain ETL pipelines for large enterprise analytics projects.",
     "posted_at": "2026-04-09", "is_open": 1},
    {"title": "Android Developer (Senior)", "company": "Hyundai Motor India", "location": "Hyderabad",
     "skills": "Android, Kotlin, MVVM, Bluetooth, IoT", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2000000, "salary_max": 2800000,
     "description": "Build connected-car Android applications for in-vehicle infotainment.",
     "posted_at": "2026-04-04", "is_open": 1},
    # Pune — various
    {"title": "Senior Node.js Developer", "company": "ThoughtWorks", "location": "Pune",
     "skills": "Node.js, TypeScript, GraphQL, PostgreSQL", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2000000, "salary_max": 2800000,
     "description": "Lead backend development for a financial services client.",
     "posted_at": "2026-04-01", "is_open": 1},
    {"title": "React Developer", "company": "Persistent Systems", "location": "Pune",
     "skills": "React, JavaScript, Redux, Jest", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1100000, "salary_max": 1700000,
     "description": "Build enterprise SaaS product UIs for US healthcare clients.",
     "posted_at": "2026-04-06", "is_open": 1},
    {"title": "QA Automation Engineer", "company": "Infosys BPM", "location": "Pune",
     "skills": "Selenium, Java, Cucumber, Jenkins", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 900000, "salary_max": 1400000,
     "description": "Design BDD test suites for insurance process automation.",
     "posted_at": "2026-04-10", "is_open": 1},
    {"title": "iOS Developer (Junior)", "company": "Bajaj Finserv", "location": "Pune",
     "skills": "Swift, iOS, UIKit, Core Data", "job_type": "full-time",
     "experience_level": "junior", "salary_min": 600000, "salary_max": 1000000,
     "description": "Build features for the Bajaj Finserv lending app on iOS.",
     "posted_at": "2026-04-12", "is_open": 1},
    {"title": "Product Manager (Mid)", "company": "Cummins India", "location": "Pune",
     "skills": "Product Management, Roadmapping, SQL, Agile", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1500000, "salary_max": 2200000,
     "description": "Own the digital tools roadmap for manufacturing operations.",
     "posted_at": "2026-03-29", "is_open": 1},
    {"title": "Python Developer (Contract)", "company": "Cognizant", "location": "Pune",
     "skills": "Python, Flask, MySQL, Docker", "job_type": "contract",
     "experience_level": "mid", "salary_min": 1000000, "salary_max": 1500000,
     "description": "3-month engagement building data ingestion APIs for a telecom client.",
     "posted_at": "2026-04-11", "is_open": 1},
    # Delhi / NCR — various
    {"title": "Senior React Developer", "company": "Policybazaar", "location": "Delhi",
     "skills": "React, TypeScript, Next.js, SEO", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 1800000, "salary_max": 2500000,
     "description": "Lead development of high-traffic insurance comparison pages.",
     "posted_at": "2026-04-03", "is_open": 1},
    {"title": "Data Scientist", "company": "MakeMyTrip", "location": "Delhi",
     "skills": "Python, scikit-learn, SQL, A/B testing", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1500000, "salary_max": 2100000,
     "description": "Build price prediction models and personalisation engines for travel bookings.",
     "posted_at": "2026-04-08", "is_open": 1},
    {"title": "DevOps Engineer", "company": "Snapdeal", "location": "Delhi",
     "skills": "AWS, Kubernetes, Helm, CI/CD", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1300000, "salary_max": 1900000,
     "description": "Manage cloud deployments and improve release pipeline reliability.",
     "posted_at": "2026-04-05", "is_open": 1},
    {"title": "Java Developer", "company": "HCL Technologies", "location": "Delhi",
     "skills": "Java, Spring MVC, Oracle DB, REST", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1000000, "salary_max": 1500000,
     "description": "Develop backend modules for a public-sector e-governance project.",
     "posted_at": "2026-04-07", "is_open": 1},
    {"title": "Node.js Developer (Remote)", "company": "Unacademy", "location": "Delhi",
     "skills": "Node.js, Express, MongoDB, Socket.io", "job_type": "remote",
     "experience_level": "mid", "salary_min": 1200000, "salary_max": 1800000,
     "description": "Build real-time live class features and notification services.",
     "posted_at": "2026-04-09", "is_open": 1},
    {"title": "Junior Python Developer", "company": "Naukri.com", "location": "Delhi",
     "skills": "Python, Django, REST APIs, PostgreSQL", "job_type": "full-time",
     "experience_level": "junior", "salary_min": 600000, "salary_max": 950000,
     "description": "Build internal tools and data processing scripts for the jobs platform.",
     "posted_at": "2026-04-13", "is_open": 1},
    # Remote / cross-city
    {"title": "Full Stack React + Node Developer", "company": "Hasura", "location": "Bangalore",
     "skills": "React, Node.js, GraphQL, PostgreSQL, Docker", "job_type": "remote",
     "experience_level": "senior", "salary_min": 2500000, "salary_max": 3500000,
     "description": "Build open-source tooling and cloud product features fully remote.",
     "posted_at": "2026-04-02", "is_open": 1},
    {"title": "ML Engineer (Remote)", "company": "Sarvam AI", "location": "Bangalore",
     "skills": "Python, PyTorch, Transformers, CUDA", "job_type": "remote",
     "experience_level": "senior", "salary_min": 3000000, "salary_max": 5000000,
     "description": "Train and fine-tune large language models for Indian language tasks.",
     "posted_at": "2026-04-05", "is_open": 1},
    {"title": "QA Engineer (Remote)", "company": "Postman", "location": "Bangalore",
     "skills": "API Testing, Postman, JavaScript, Newman", "job_type": "remote",
     "experience_level": "mid", "salary_min": 1400000, "salary_max": 2000000,
     "description": "Test Postman's API collaboration platform features and integrations.",
     "posted_at": "2026-04-11", "is_open": 1},
    {"title": "Senior Product Manager", "company": "Razorpay", "location": "Bangalore",
     "skills": "Product Management, Payments, SQL, Roadmapping", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 3000000, "salary_max": 4000000,
     "description": "Own Razorpay's merchant dashboard product from strategy to launch.",
     "posted_at": "2026-04-04", "is_open": 1},
    {"title": "React Native Developer", "company": "Ola Electric", "location": "Bangalore",
     "skills": "React Native, TypeScript, iOS, Android", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1400000, "salary_max": 2000000,
     "description": "Build the companion app for Ola Electric scooters.",
     "posted_at": "2026-04-08", "is_open": 1},
    {"title": "Backend Engineer (Go)", "company": "Stripe", "location": "Bangalore",
     "skills": "Go, PostgreSQL, REST APIs, gRPC", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2800000, "salary_max": 3800000,
     "description": "Build payment processing infrastructure serving millions of transactions.",
     "posted_at": "2026-04-04", "is_open": 1},
    {"title": "Cloud Infrastructure Specialist", "company": "Atlassian", "location": "Hyderabad",
     "skills": "AWS, Terraform, Python, Kubernetes", "job_type": "full-time",
     "experience_level": "senior", "salary_min": 2600000, "salary_max": 3600000,
     "description": "Design and maintain multi-region cloud infrastructure for Atlassian Cloud.",
     "posted_at": "2026-04-09", "is_open": 1},
    {"title": "Full Stack Developer", "company": "Grofers", "location": "Mumbai",
     "skills": "JavaScript, React, Node.js, MongoDB", "job_type": "full-time",
     "experience_level": "mid", "salary_min": 1300000, "salary_max": 1900000,
     "description": "Build features across web and mobile for grocery delivery platform.",
     "posted_at": "2026-04-07", "is_open": 1},
    # Closed job (for testing is_open filter)
    {"title": "Archived Python Role", "company": "OldCo", "location": "Pune",
     "skills": "Python", "job_type": "full-time", "experience_level": "mid",
     "salary_min": 1000000, "salary_max": 1500000,
     "description": "This position is closed.", "posted_at": "2025-01-01", "is_open": 0},
]
